{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "synchro-iobeya-github.labels" . | nindent 4 }}
type: Opaque
stringData:
  ACCESS_KEY: "{{ .Values.secret.env.ACCESS_KEY }}"
  GITHUB_TOKEN: "{{ .Values.secret.env.GITHUB_TOKEN }}"
  IOBEYA_TOKEN: "{{ .Values.secret.env.IOBEYA_TOKEN }}"
{{- end }}
